apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: computesdk-system
  labels:
    app: api-service
spec:
  type: ClusterIP
  selector:
    app: computesdk-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
