apiVersion: apps/v1
kind: Deployment
metadata:
  name: computesdk-api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: computesdk-api
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: ENVIRONMENT
              value: "production"
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15