apiVersion: apps/v1
kind: Deployment
metadata:
  name: computesdk-gateway
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: computesdk-gateway
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: ENVIRONMENT
              value: "production"