apiVersion: apps/v1
kind: Deployment
metadata:
  name: computesdk-gateway
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: computesdk-gateway
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "750m"
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: ENVIRONMENT
              value: "staging"