apiVersion: apps/v1
kind: Deployment
metadata:
  name: computesdk-gateway
  namespace: computesdk-system
  labels:
    app: computesdk-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computesdk-gateway
  template:
    metadata:
      labels:
        app: computesdk-gateway
    spec:
      initContainers:
        - name: wait-for-api-service
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z api-service 8080; do echo waiting for api-service; sleep 2; done;']
      containers:
        - name: computesdk-gateway
          image: ghcr.io/computesdk/gateway:latest
          ports:
            - containerPort: 8080 # Assuming gateway listens on 8080
          env:
            # Example: Configuration for api-service if gateway needs it
            - name: API_SERVICE_HOST
              value: "api-service.computesdk-system.svc.cluster.local"
            - name: API_SERVICE_PORT
              value: "8080" # Assuming API service runs on port 8080
          resources:
