apiVersion: apps/v1
kind: Deployment
metadata:
  name: computesdk-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: computesdk-api
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: ENVIRONMENT
              value: "development"