apiVersion: apps/v1
kind: Deployment
metadata:
  name: computesdk-sidekick
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: computesdk-sidekick
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: ENVIRONMENT
              value: "development"