apiVersion: apps/v1
kind: Deployment
metadata:
  name: computesdk-sidekick
  namespace: computesdk-system
  labels:
    app: computesdk-sidekick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computesdk-sidekick
  template:
    metadata:
      labels:
        app: computesdk-sidekick
    spec:
      containers:
        - name: computesdk-sidekick
          image: computesdk/sidekick:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      terminationGracePeriodSeconds: 30